name: stabilisation

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Restore
        run: dotnet restore --use-lock-file
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Unit tests
        run: dotnet test tests/CORIS.Tests --configuration Release --no-build --verbosity normal
      - name: Vulkan headless smoke test
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
        run: dotnet run --project src/CORIS.Sim --configuration Release -- --vulkan-test --vk-validate